export const initialProducts = [
  {
    id: "1",
    name: "HP EliteBook 840 G8",
    brand: "HP",
    category: "business",
    model: "EliteBook 840 G8",
    processor: "Intel Core i7-1165G7",
    generation: "11th Gen",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14.0\" FHD (1920x1080) IPS Anti-Glare 400 nits",
    graphics: "Intel Iris Xe Graphics",
    battery: "Up to 8 Hours (53Wh Fast Charge)",
    os: "Windows 11 Pro Licensed",
    condition: "Like New (10/10)",
    charger: true,
    warranty: "1 Month Replacement + 6 Months Service Warranty",
    price: 118000,
    oldPrice: 130000,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-18",
    rating: 4.9,
    reviewsCount: 24,
    images: [
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80"
    ],
    description: "The HP EliteBook 840 G8 is an ultra-premium business powerhouse built with precision-crafted aluminum chassis, powerful 11th Gen Core i7 processor, and enterprise-grade security features.",
    keyFeatures: [
      "Aluminum CNC precision unibody design",
      "Bang & Olufsen tuned audio with quad speakers",
      "Backlit spill-resistant keyboard",
      "Thunderbolt 4 / USB Type-C high speed ports"
    ]
  },
  {
    id: "2",
    name: "Dell Latitude 7420 Carbon Fiber",
    brand: "Dell",
    category: "business",
    model: "Latitude 7420",
    processor: "Intel Core i7-1185G7 vPro",
    generation: "11th Gen",
    ram: "16GB LPDDR4x",
    storage: "512GB PCIe M.2 SSD",
    display: "14.0\" 4K UHD (3840x2160) Super Low Power ComfortView Plus",
    graphics: "Intel Iris Xe Graphics",
    battery: "Up to 7.5 Hours (63Wh ExpressCharge)",
    os: "Windows 11 Pro",
    condition: "Excellent (9.5/10)",
    charger: true,
    warranty: "1 Month Replacement Warranty",
    price: 125000,
    oldPrice: 138000,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-16",
    rating: 4.8,
    reviewsCount: 19,
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Dell Latitude 7420 delivers enterprise-class performance in a sleek carbon-fiber build.",
    keyFeatures: [
      "Lightweight Carbon Fiber chassis weighing only 1.22 kg",
      "Full HD IR Camera with ExpressSign-in",
      "Dual Thunderbolt 4 with Power Delivery"
    ]
  },
  {
    id: "3",
    name: "Lenovo ThinkPad T14 Gen 2",
    brand: "Lenovo",
    category: "business",
    model: "ThinkPad T14 Gen 2",
    processor: "AMD Ryzen 7 PRO 5850U (8 Cores, 16 Threads)",
    generation: "Ryzen 5000 Series",
    ram: "16GB DDR4 (Upgradable)",
    storage: "512GB NVMe PCIe Gen3 SSD",
    display: "14.0\" FHD (1920x1080) IPS 300 nits Anti-Glare",
    graphics: "AMD Radeon Vega Graphics",
    battery: "Up to 9 Hours (50Wh Rapid Charge)",
    os: "Windows 11 Pro",
    condition: "Excellent (9.5/10)",
    charger: true,
    warranty: "1 Month Warranty",
    price: 112000,
    oldPrice: 122000,
    stock: "available",
    featured: false,
    onSale: false,
    dateAdded: "2026-08-10",
    rating: 4.9,
    reviewsCount: 31,
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Legendary ThinkPad durability meets powerful 8-core AMD Ryzen 7 processing.",
    keyFeatures: [
      "MIL-STD-810H military certified ruggedness",
      "ThinkShutter webcam privacy physical slider",
      "Legendary ergonomic ThinkPad keyboard"
    ]
  },
  {
    id: "4",
    name: "Dell Precision 5550 Mobile Workstation",
    brand: "Dell",
    category: "business",
    model: "Precision 5550",
    processor: "Intel Core i7-10850H (6 Cores 5.1GHz Turbo)",
    generation: "10th Gen H-Series",
    ram: "32GB DDR4 High Speed",
    storage: "1TB NVMe PCIe SSD",
    display: "15.6\" 4K UHD+ (3840x2400) Touch InfinityEdge 500 nits HDR",
    graphics: "NVIDIA Quadro T2000 4GB GDDR6 Dedicated",
    battery: "Up to 5.5 Hours (86Wh)",
    os: "Windows 11 Pro for Workstations",
    condition: "Like New (9.8/10)",
    charger: true,
    warranty: "1 Month Replacement Warranty",
    price: 185000,
    oldPrice: 205000,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-19",
    rating: 5.0,
    reviewsCount: 14,
    images: [
      "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80"
    ],
    description: "A creator workstation in an XPS-like ultrathin body with NVIDIA Quadro graphics.",
    keyFeatures: [
      "Bezel-less 16:10 4K UHD+ Touch display",
      "NVIDIA Quadro T2000 for AutoCAD, SolidWorks, Premiere"
    ]
  },
  {
    id: "6",
    name: "Dell Latitude 5400",
    brand: "Dell",
    category: "student",
    model: "Latitude 5400",
    processor: "Intel Core i5-8365U",
    generation: "8th Gen",
    ram: "8GB DDR4",
    storage: "256GB SSD",
    display: "14.0\" FHD (1920x1080) Anti-Glare",
    graphics: "Intel UHD 620",
    battery: "Up to 5 Hours",
    os: "Windows 10/11 Pro",
    condition: "Good (8.5/10)",
    charger: true,
    warranty: "1 Month Warranty",
    price: 46000,
    oldPrice: 52000,
    stock: "available",
    featured: false,
    onSale: false,
    dateAdded: "2026-08-01",
    rating: 4.6,
    reviewsCount: 38,
    images: [
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Affordable and durable student workhorse for online classes, Zoom, and MS Office.",
    keyFeatures: [
      "Strong reinforced polycarbonate body",
      "Smooth typing keyboard with backlight"
    ]
  },
  {
    id: "9",
    name: "ASUS ROG Strix G15",
    brand: "Asus",
    category: "gaming",
    model: "G513QC",
    processor: "AMD Ryzen 7 5800H (8 Cores, 16 Threads 4.4GHz)",
    generation: "Ryzen 5000 Gaming",
    ram: "16GB DDR4 3200MHz",
    storage: "512GB M.2 NVMe PCIe SSD",
    display: "15.6\" FHD (1920x1080) 144Hz IPS 3ms Adaptive-Sync",
    graphics: "NVIDIA GeForce RTX 3050 4GB GDDR6",
    battery: "Up to 5 Hours",
    os: "Windows 11 Home",
    condition: "Like New (9.8/10)",
    charger: true,
    warranty: "1 Month Replacement Warranty",
    price: 195000,
    oldPrice: 215000,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-19",
    rating: 5.0,
    reviewsCount: 33,
    images: [
      "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Extreme gaming and rendering performance with Ryzen 7 5800H and RTX 3050 graphics.",
    keyFeatures: [
      "Ultra-fluid 144Hz eSports display",
      "NVIDIA DLSS & Ray Tracing enabled",
      "4-Zone RGB Backlit Keyboard"
    ]
  },
  {
    id: "13",
    name: "HP Chromebook x360 14c Touch",
    brand: "HP",
    category: "chromebook",
    model: "Chromebook x360 14c",
    processor: "Intel Core i3-10110U",
    generation: "10th Gen",
    ram: "8GB DDR4",
    storage: "64GB eMMC + MicroSD Expansion",
    display: "14.0\" FHD (1920x1080) IPS Corning Gorilla Glass Touchscreen",
    graphics: "Intel UHD Graphics",
    battery: "Up to 11 Hours (All Day Battery)",
    os: "Chrome OS with Google Play Store",
    condition: "Like New (10/10)",
    charger: true,
    warranty: "1 Month Warranty",
    price: 42000,
    oldPrice: 48000,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-14",
    rating: 4.8,
    reviewsCount: 39,
    images: [
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=800&q=80"
    ],
    description: "Premium metal 2-in-1 convertible Chromebook with Bang & Olufsen sound.",
    keyFeatures: [
      "360-degree convertible hinge",
      "Supports all Google Play Store Android Apps",
      "Up to 11 hours battery life"
    ]
  },
  {
    id: "17",
    name: "Original HP 65W USB Type-C Fast Charger",
    brand: "HP",
    category: "accessory",
    model: "65W Type-C AC Adapter",
    processor: "N/A",
    generation: "N/A",
    ram: "N/A",
    storage: "N/A",
    display: "N/A",
    graphics: "N/A",
    battery: "N/A",
    os: "Universal Compatibility",
    condition: "Brand New Box Packed",
    charger: true,
    warranty: "6 Months Replacement Warranty",
    price: 4500,
    oldPrice: 5500,
    stock: "available",
    featured: true,
    onSale: true,
    dateAdded: "2026-08-15",
    rating: 4.9,
    reviewsCount: 65,
    images: [
      "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80"
    ],
    description: "100% Original HP 65W Smart USB Type-C Power Adapter.",
    keyFeatures: [
      "Original HP OEM Adapter with thick copper cable",
      "Automatic voltage switching (5V/9V/12V/15V/20V)"
    ]
  }
];
